// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Required by `prisma migrate dev` and by the CI drift check
    // (`prisma migrate diff --from-migrations`). Unset at runtime; the app
    // never connects to it.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
